# Generated by Django 4.1.7 on 2023-03-17 16:20

import apps.orders.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_customer_date_of_birth'),
        ('products', '0003_rename_facets_facet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=75)),
                ('order_number', models.CharField(default=apps.orders.models.generate_order_number, max_length=9)),
                ('total', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('delivery_status', models.CharField(choices=[('NEW ORDER', 'New order'), ('HANDLING', 'Handling'), ('TRANSFERRED TO THE DS', 'Transferred to the delivery service'), ('BEING DELIVERED', 'Being delivered'), ('WAITING FOR THE CLIENT AT THE PP', 'Waiting for the client at the pick-up point'), ('COMPLETED', 'Completed')], default='NEW ORDER', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('customer_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customeraddress')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_option', models.IntegerField(default=0, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
