# Generated by Django 4.1.7 on 2023-03-21 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_phone_numbers_customer_phone_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.customer'),
            preserve_default=False,
        ),
    ]
