# Generated by Django 4.1.7 on 2023-03-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('provider', models.CharField(max_length=60)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('HANDLING', 'Handling'), ('PAID', 'Paid')], default='UNPAID', max_length=60)),
                ('transaction_id', models.CharField(max_length=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
        ),
    ]
