# Generated by Django 4.1.7 on 2023-03-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_remove_facets_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facets',
            new_name='Facet',
        ),
    ]
