# Generated by Django 4.1.7 on 2023-03-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_facets_facet'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
